### ISSUE TITLE
Is this crate maintained / is bincode2 the successor?

### ISSUE THREAD

**Issue by robinmoussu** [servo/bincode#318]
[bincode2](https://github.com/pravega/bincode2) claims to be the successor of bincode. Is it effectively the case. I noticed that this repository has new commit since bincode2 forked it, so I can't be sure. If yes, would it be possible to add a link to bincode2 in the Readme. If no, would it be possible to add a note somewhere?

**Comment by ZoeyR** [comment]
This crate is still maintained actively. bincode2 was created when no one stepped up to the plate to review large PRs but that has since changed. I don't think it really makes sense to mention bincode2 in our readme anywhere. It would make more sense for bincode2 to mention that it is now defunct and should point back to this repo.

**Comment by robinmoussu** [comment]
Thanks for clarifying the situation.
